plugins:
  discourse_no_class_template_enabled:
    client: true
    default: false
  discourse_no_class_template_template:
    default: |
      ## 1. 问题描述

      ## 2. 环境信息
      > 直接粘贴`fastfetch --logo none`的输出即可

      ## 3. 错误信息 / 日志 / 截图
      > 请直接粘贴文本形式或者上传日志文件，截图仅用于文字无法表达的界面问题。

      ## 4. 已尝试的解决方法
      > 列出你做过的尝试和结果，避免别人重复给出你试过的建议。

      > 另外，如果你完全不清楚该怎么办，只写问题描述也没有问题。

    textarea: true
    client: true
