plugins:
  discourse_no_class_template_enabled:
    client: true
    default: false
  discourse_no_class_template_template:
    default: |
      ## 1. 问题描述
      > 用 2–4 句话说清楚：你想做什么、发生了什么、哪里不对。

      我想要 **[目标/预期行为]**,但是 **[实际发生的情况]**
      这个问题 **[总是出现 / 偶尔出现 / 在某次更新或改动后开始出现]**

      ## 2. 环境信息
      操作系统及版本：
      使用的桌面环境（例如：`KDE`， `GNOME`，`niri`）：
      相关软件及版本：
      硬件型号（如果与硬件相关）：
      最近的系统变更（例如:更新了系统、安装了某软件、改了设置）：
      > 提示：使用`fastfetch --logo none`可以获取以上大部分信息，你可以把以上`操作系统及版本：`等内容删除，直接粘贴文本形式的输出，但不要提供输出截图。

      ## 3. 复现步骤（如果不清楚，可以跳过）
      > 别人按你的步骤能重现问题，就更容易帮到你。
      1.
      2.
      3.
      4.
 
      ## 4. 错误信息 / 日志 / 截图
      > 请直接粘贴文本形式，截图仅用于文字无法表达的界面问题。
      > 如果你认为该问题与内核相关，使用`sudo dmesg`可以获取内核日志。
      > 如果信息超过100行，请不要将其直接粘贴到下面，而应该其放入文件中，然后上传该文件。
      > 但要注意: 不要将所有信息都放在一个文件中，请分类保存，例如：`app.log` `dmesg.log`，避免信息混乱。
      ```
      [在此粘贴完整的错误信息或相关日志]
      ```

      ## 5. 已尝试的解决方法
      > 列出你做过的尝试和结果，避免别人重复给出你试过的建议。

      ## 问题发布前确认：
      1. 我已搜索过类似问题，并在正文中说明了差异。
      2. 所有信息尽可能以**纯文本**形式提供，而不是截图。

    textarea: true
    client: true
